version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-typescript-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8080  # o segredo está aqui!
    depends_on:
      - backend
    command: npm run dev -- --host
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
